### PR TITLE
Draft Completion Review

### PR DESCRIPTION
**Pull request by lifengyan-amber**

### CODE REVIEW

**Comment by lifengyan-amber** [comment]
Please review the additional features added and let me know if you see any issues.

**Review by WilliamZ624 — COMMENTED** [review]
testing frontend using puppeteer. Found the absense of "log out" function.

**Comment by WilliamZ624** [comment]
testing frontend, "ant drop down trigger" problem detected.

**Comment by lifengyan-amber** [comment]
> testing frontend using puppeteer. Found the absense of "log out" function.

Bug fixed

**Comment by lifengyan-amber** [comment]
> 

Problem fixed with Selenium webdriver

**Pull request closed without merging**
